const data = {
    products: [
      {
        _id: '1',
        name: 'Roadster Men Burgandy Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 699,
        countInStock: 6,
        brand: 'Roadster',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Harvard Men Pink Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 899,
        countInStock: 7,
        brand: 'Harvard',
        rating: 4.5,
        numReviews: 15,
        description: 'High quality product',
      },
      {
        _id: '3',
        name: 'Roadster Blue Men Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 649,
        countInStock: 8,
        brand: 'Roadster',
        rating: 4.5,
        numReviews: 17,
        description: 'High quality product',
      },
      {
        _id: '4',
        name: 'Mast & Harbour Men Blue & White T-shirt',
        category: 'T-shirt',
        image: '/images/p4.jpg',
        price: 549,
        countInStock: 10,
        brand: 'Mast & Harbour',
        rating: 5,
        numReviews: 17,
        description: 'High quality product',
      },
      {
        _id: '5',
        name: 'WROGN Men Green T-shirt',
        category: 'T-shirt',
        image: '/images/p5.jpg',
        price: 999,
        countInStock: 12,
        brand: 'WROGN',
        rating: 4,
        numReviews: 10,
        description: 'High quality product',
      },
      {
        _id: '6',
        name: 'WROGN Men White T-shirt',
        category: 'T-shirt',
        image: '/images/p6.jpg',
        price: 1099,
        countInStock: 6,
        brand: 'WROGN',
        rating: 4.5,
        numReviews: 15,
        description: 'High quality product',
      },
    ],
  };
  export default data;